name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit

    - uses: actions/first-interaction@3c71ce730280171fd1cfb57c00c774f8998586f7 # v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks a lot for opening your first issue with us! 🧡 We''ll get back to you shortly! ⏳ If it was a _Support Request_, please consider asking on the [community chat](../#troubleshooting-) next time! 💬'
        pr-message: 'Thanks a lot for your contribution! 💖 This seems to be you first PR! 🌠 If it''s getting merged & complies with our [contribution guidelines](../blob/master/CONTRIBUTING.md), you are probably eligible to some free stickers! 🎁'
